#!/usr/bin/python3
from optparse import OptionParser
import Utils as ut
import sys
import os
import time

## Line buffer stdout and stderr
sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', buffering=1)
sys.stderr = os.fdopen(sys.stderr.fileno(), 'w', buffering=1)
##
## Parse options.
##
cHelp  = "SCiMMA client configuration file"
sHelp  = "SCiMMA server URL"
sUrl   = "kafka://dev.hop.scimma.org:9092/heartbeat"
p = OptionParser(usage="Usage: %prog [options]")
p.add_option("",   "--scimma", dest="scimmaUrl", default=sUrl, help=sHelp)
p.add_option("-F", "--config", dest="scimmaConfFile", default="~/shared/kafkacat.conf", help=cHelp)
(o, a) = p.parse_args()

scimmaUrl      = o.scimmaUrl
scimmaConfFile = os.path.expanduser(o.scimmaConfFile)

print("hopBeat starting")
print("SCiMMA server URL:  %s"   % scimmaUrl)
print("SCiMMA config file: %s\n" % scimmaConfFile)

sC = ut.ScimmaConnection(scimmaUrl, scimmaConfFile)
sC.open()

heartbeats = ["listen", "Listen", "LISTEN", "listen to my heart beat"]
count=0
seq=0
while (True):
    et = int(time.time())
#    message = "{\"timestamp\": %d, \"count\": %d, \"msg\": \"%s\"}" % (et, count, heartbeats[count%4])
    message = { "timestamp" : et,
                "count" : count,
                "beat"  : heartbeats[count%4] }
    sC.write(message);
    print(message)
    count = count + 1
    sleep(30)
