name: Release
on:
  push:
    tags:
      - 'version-*'

jobs:
  release:
    runs-on: ubuntu-18.04
    name:    release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make
        run:  make
      - name: install_aws
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin
      - name: push
        env:
          AWS_ACCESS_KEY: ${{ secrets.PUSHUSER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PUSHSECRET }}
          AWS_DEFAULT_REGION: us-west-2
        run: make push
